### ISSUE TITLE
Not working with Flutter 3.29.1 and MacOS 15.3.2

### ISSUE THREAD

**Issue by jodinathan** [espresso3389/pdfrx#327]
it stopped working after upgrading Flutter:

```
In file included from /Users/x/.pub-cache/hosted/pub.dev/pdfrx-1.1.12/darwin/Classes/pdfrx.cpp:3:
/Users/x/.pub-cache/hosted/pub.dev/pdfrx-1.1.12/darwin/Classes/../../src/pdfium_interop.cpp:5:10: fatal error: 'fpdfview.h' file not found
    5 | #include <fpdfview.h>
      |          ^~~~~~~~~~~~
1 error generated.
```

did flutter clean but got same error

**Comment by espresso3389** [comment]
Could you please once try `dart pub cache clean`?

**Comment by jodinathan** [comment]
it worked, thank you
